"""Add User and relations

Revision ID: 06e1df4f4726
Revises: 2f8f68206adf
Create Date: 2026-08-04 21:49:20.117481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e1df4f4726'
down_revision: Union[str, Sequence[str], None] = '2f8f68206adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'])
    op.add_column('budgets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'])
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.add_column('expenses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'])
    op.add_column('incomes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incomes', 'users', ['user_id'], ['id'])
    op.add_column('investments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'investments', 'users', ['user_id'], ['id'])
    op.add_column('recurring_transactions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recurring_transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recurring_transactions', type_='foreignkey')
    op.drop_column('recurring_transactions', 'user_id')
    op.drop_constraint(None, 'investments', type_='foreignkey')
    op.drop_column('investments', 'user_id')
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_column('incomes', 'user_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'user_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'user_id')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'user_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
