"""Add investment table

Revision ID: 2f8f68206adf
Revises: f11f97eff97c
Create Date: 2026-08-04 21:26:39.663507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8f68206adf'
down_revision: Union[str, Sequence[str], None] = 'f11f97eff97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('ticker_symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_purchase_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_asset_name'), 'investments', ['asset_name'], unique=False)
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_asset_name'), table_name='investments')
    op.drop_table('investments')
    # ### end Alembic commands ###
