"""Make user_id not nullable

Revision ID: 528f6ab8a7d4
Revises: 06e1df4f4726
Create Date: 2026-08-04 21:57:50.921705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528f6ab8a7d4'
down_revision: Union[str, Sequence[str], None] = '06e1df4f4726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('budgets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('categories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('incomes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('investments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recurring_transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recurring_transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('investments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('incomes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('budgets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
