"""Add receipt_url to expenses

Revision ID: f11f97eff97c
Revises: 094f5f6d32b7
Create Date: 2026-08-02 23:21:00.760696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11f97eff97c'
down_revision: Union[str, Sequence[str], None] = '094f5f6d32b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('receipt_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'receipt_url')
    # ### end Alembic commands ###
